### PR TITLE
WIP Start Page

### PR DESCRIPTION
**Pull request by Armaldio**

### CODE REVIEW

**Comment by TheRealDannyyy** [comment]
Will give it a go tomorrow.

**Comment by Armaldio** [comment]
It's not done yet, you can wait until I remove WIP from the title if you
want

Le lun. 28 mai 2018 à 02:12, TheRealDannyyy <notifications@github.com> a
écrit :

**Comment by TheRealDannyyy** [comment]
Do you want me to pull this?

**Comment by Armaldio** [comment]
You can do it now if you want, but it's still WIP so it might not be necessary

**Comment by TheRealDannyyy** [comment]
Can't merge anyway because of failing status.

**Comment by Armaldio** [comment]
You **MUST** not merge!

**Comment by TheRealDannyyy** [comment]
I don't get the difference between merging and closing.

**Pull request merged**
