### PR TITLE
Settings page

### PR DESCRIPTION
**Pull request by Armaldio**
add settings page
add menu on menu click

### CODE REVIEW

**Comment by Armaldio** [comment]
@TheRealDannyyy I've added a Settings page
You can start editiing the template menu I've made
And if you feel, designing the layout of the settign page (didn't had the time to do more)

**Comment by TheRealDannyyy** [comment]
You can do the layout whenever you go the time to. I still don't understand how it works in full detail.

**Comment by TheRealDannyyy** [comment]
Remember to open the settings page in a seprate window, not an in-app window but actual windows window.

Also some errors while running preview:
extension errors

**Comment by TheRealDannyyy** [comment]
The settings menu is good but it's still not in a pop-up window. Would be nice if you can add that.

**Comment by Armaldio** [comment]
@TheRealDannyyy Should support fontawesome now

**Comment by Armaldio** [comment]
use ` <v-icon>put here classes you see on the website</v-icon>`

**Comment by Armaldio** [comment]
Added settings men,u, just visual for now, no interactions
Also try to avoid inline css please

**Comment by TheRealDannyyy** [comment]
You told me it's alright, any problems caused by it?

**Comment by Armaldio** [comment]
It's alright but we can try to keep the styles all at the same place (at the bottom of the file, inside the `style` tag)

**Comment by TheRealDannyyy** [comment]
I can move every style element as classes/ids below if you want me to.

**Comment by Armaldio** [comment]
Yeah that will be cleaner

**Comment by Armaldio** [comment]
The settings are not fully done, but the menu is there, merging this for now

**Pull request merged**
